#pragma config(Motor,  motor1,          DriverFront,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          PassengerFront, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          DriverBack,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          PassengerBaclk, tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	x=0;
	while(x<1)
	{
		tankControl(ChD, ChA, 10);
	}



}
